// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(compound) {
    var defaultModules, developmentModules;
    defaultModules = ['jugglingdb', 'co-assets-compiler'];
    developmentModules = [];
    if (compound.app.get('env') === 'development') {
      developmentModules = ['ejs-ext', 'seedjs', 'co-generators'];
    }
    if (typeof window === "undefined" || window === null) {
      return defaultModules.concat(developmentModules).map(require);
    } else {
      return [];
    }
  };

}).call(this);
