// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    development: {
      driver: "memory"
    },
    test: {
      driver: "memory"
    },
    production: {
      driver: "memory"
    }
  };

}).call(this);
