// Generated by CoffeeScript 1.7.1
(function() {
  global.models = {};

  global.models.MySpellChecker = require('../app/models/myspellchecker');

  global.helper = require('../app/helpers/helper');

  global.logger = helper.Logger;

}).call(this);
