// Generated by CoffeeScript 1.7.1
(function() {
  var express;

  express = require('express');

  module.exports = function(compound) {
    var app;
    app = compound.app;
    return app.configure('development', function() {
      app.enable('log actions');
      app.enable('env info');
      app.enable('watch');
      app.enable('force assets compilation');
      app.use(express.errorHandler({
        dumpExceptions: true,
        showStack: true
      }));
      return app.enable('quiet');
    });
  };

}).call(this);
