// Generated by CoffeeScript 1.7.1
(function() {
  var SpellChecker;

  SpellChecker = models.MySpellChecker;

  action('check_spelling', function() {
    var sc;
    if (!/^[A-Za-z]+$/.test(req.params.word)) {
      return send(422, {
        error: "Only letters are accepted"
      });
    }
    sc = new SpellChecker(req.params.word);
    return sc.check(function(error, response) {
      return send(200, response);
    });
  });

}).call(this);
